server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          hsdp:
            client-id: keymaster
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: post
        provider:
          hsdp:
            token-uri: "https://iam-client-test.us-east.philips-healthsuite.com/authorize/oauth2/token?api-version=2"
            authorization-uri: "https://iam-client-test.us-east.philips-healthsuite.com/authorize/oauth2/authorize?api-version=2"
            user-info-uri: "https://iam-client-test.us-east.philips-healthsuite.com/authorize/oauth2/userinfo?api-version=2"
            user-name-attribute: sub
            jwk-set-uri: "https://iam-client-test.us-east.philips-healthsuite.com/authorize/oauth2/jwks?api-version=1"